name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Upload code
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.4'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r ./backend/requirements.txt
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   concurrency: test-job
  #   steps:
  #   - name: Build Docker Image
  #     run: |
  #       docker build -t myapp:latest .


