name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Get Source code step
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # Build step
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.4'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r backend/requirements.txt

    - name: Run npm install + build
      run: |
        cd frontend
        npm install
        npm run build

    # Run tests
    - name: Run Tests
      run: |
        source .venv/bin/activate
        cd backend
        pytest

    # - name: Build Docker Image
    #   run: |
    #     docker build -t myapp:latest .

