name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  get-code:
    runs-on: ubuntu-latest
    concurrency: source-job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

  build:
    needs: get-code
    runs-on: ubuntu-latest
    concurrency: build-job
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.4'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r ./backend/requirements.txt

    - name: Run npm install + build
      run: |
        cd frontend
        npm install
        npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    concurrency: test-job
    steps:
    - name: Run Tests
      run: |
        source .venv/bin/activate
        cd backend
        pytest

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   concurrency: test-job
  #   steps:
  #   - name: Build Docker Image
  #     run: |
  #       docker build -t myapp:latest .

