name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

  build:
    needs: get-code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.4'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r ./backend/requirements.txt

    - name: Run npm install + build
      run: |
        cd frontend
        npm install
        npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout Code
    #   uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.10.4'

    # - name: Install dependencies
    #   run: |
    #     python -m venv .venv
    #     source .venv/bin/activate
    #     pip install --upgrade pip
    #     pip install -r ./backend/requirements.txt

    - name: Run Tests
      run: |
        source .venv/bin/activate
        cd backend
        pytest

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v2

    # - name: Build Docker Image
    #   run: |
    #     docker build -t myapp:latest .



