name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Upload code
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .

  build:
    needs: source
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          if [ -f "./backend/requirements.txt" ]; then
            pip install -r ./backend/requirements.txt
          else
            echo "Error: requirements.txt not found in ./backend"
            exit 1
          fi
      - name: Upload code and dependencies
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: |
            .
            .venv

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download code and dependencies
        uses: actions/download-artifact@v3
        with:
          name: code
          path: |
            .
            .venv
      - name: Run tests
        run: |
          source .venv/bin/activate
          cd ./backend 
          pytest

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download code and environment
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: code-and-env
  #         path: .
  #     - name: Build Docker Image
  #       run: |
  #         docker build -t myapp:latest .
